//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34003
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Phone.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Phone.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid FilterMode enumeration value. The value must be one of the defined AutoCompleteFilterMode values to be accepted..
        /// </summary>
        internal static string AutoComplete_OnFilterModePropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnFilterModePropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid maximum drop down height value &apos;{0}&apos;. The value must be greater than or equal to zero..
        /// </summary>
        internal static string AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMaxDropDownHeightPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid MinimumPopulateDelay value &apos;{0}&apos;. The value must be greater than or equal to zero..
        /// </summary>
        internal static string AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("AutoComplete_OnMinimumPopulateDelayPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot set read-only property SearchText..
        /// </summary>
        internal static string AutoComplete_OnSearchTextPropertyChanged_InvalidWrite {
            get {
                return ResourceManager.GetString("AutoComplete_OnSearchTextPropertyChanged_InvalidWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid type. Argument must be of the type System.DateTime..
        /// </summary>
        internal static string InvalidDateTimeArgument {
            get {
                return ResourceManager.GetString("InvalidDateTimeArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid operation. The IsExpanded property cannot be modified when IsNonExpandable is set to true..
        /// </summary>
        internal static string InvalidExpanderViewOperation {
            get {
                return ResourceManager.GetString("InvalidExpanderViewOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid argument. The number of months should be greater than 1 and less than 12..
        /// </summary>
        internal static string InvalidNumberOfMonths {
            get {
                return ResourceManager.GetString("InvalidNumberOfMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid argument. The number of time units should be greater than 1..
        /// </summary>
        internal static string InvalidNumberOfTimeUnits {
            get {
                return ResourceManager.GetString("InvalidNumberOfTimeUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SelectedIndex must always be set to a valid value..
        /// </summary>
        internal static string InvalidSelectedIndex {
            get {
                return ResourceManager.GetString("InvalidSelectedIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SelectedItem must always be set to a valid value..
        /// </summary>
        internal static string InvalidSelectedItem {
            get {
                return ResourceManager.GetString("InvalidSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid argument. Future dates and times are not supported..
        /// </summary>
        internal static string NonSupportedDateTime {
            get {
                return ResourceManager.GetString("NonSupportedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The RoutedPropertyChangingEvent cannot be canceled!.
        /// </summary>
        internal static string RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation {
            get {
                return ResourceManager.GetString("RoutedPropertyChangingEventArgs_CancelSet_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos; is unable to convert &apos;{1}&apos; to &apos;{2}&apos;..
        /// </summary>
        internal static string TypeConverters_Convert_CannotConvert {
            get {
                return ResourceManager.GetString("TypeConverters_Convert_CannotConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &apos;{0}&apos; cannot convert from &apos;{1}&apos;..
        /// </summary>
        internal static string TypeConverters_ConvertFrom_CannotConvertFromType {
            get {
                return ResourceManager.GetString("TypeConverters_ConvertFrom_CannotConvertFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type was unexpected..
        /// </summary>
        internal static string UnexpectedType {
            get {
                return ResourceManager.GetString("UnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid length value &apos;{0}&apos;..
        /// </summary>
        internal static string WrapPanel_OnItemHeightOrWidthPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("WrapPanel_OnItemHeightOrWidthPropertyChanged_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid Orientation value &apos;{0}&apos;..
        /// </summary>
        internal static string WrapPanel_OnOrientationPropertyChanged_InvalidValue {
            get {
                return ResourceManager.GetString("WrapPanel_OnOrientationPropertyChanged_InvalidValue", resourceCulture);
            }
        }
    }
}
